[package]
name = "lux-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
wgpu = "27.0"
egui = "0.33"
egui-wgpu = "0.33"
egui-winit = "0.33"
tokio = { version = "1.37", features = ["full"] }
log = "0.4"
env_logger = "0.11"
egui-phosphor = "0.11"
lux-core = { path = "../lux-core" }
notify = "6.1.1"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
lazy_static = "1.5.0"
tree-sitter = "0.26.7"
tree-sitter-rust = "0.24.1"
