[package]
name = "lux-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
log = "0.4"
env_logger = "0.11"
egui-phosphor = "0.11"
lux-core = { path = "../lux-core" }
notify = "6.1.1"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
lazy_static = "1.5.0"
tree-sitter = "0.26.7"
tree-sitter-rust = "0.24.1"
syntect = "5.3.0"
config = "0.15.22"
font-kit = "0.14.3"
eframe = "0.33"
ignore = "0.4.25"
arboard = "3"

[dev-dependencies]
tempfile = "3"
